version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "example-dolab-severless"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wxmnd1hf4jb7"
s3_prefix = "example-dolab-severless"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
